---
title: "RWorksheet_Lumauag#4a"
author: "Matt Andrei Lumauag"
date: "2024-10-15"
output: pdf_document
---
```{r}
#1
#a
shoesize <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0)
height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0)
gender <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")
householdData <- data.frame(shoesize, height, gender)
names(householdData) <- c("Shoesize", "Height", "Gender")
householdData
```

```{r}
#b
householdDataMale <- subset(householdData, Gender == "M")
householdDataMale

householdDataFemale <- subset(householdData, Gender == "F")
householdDataFemale
```
```{r}
#c
mean(shoesize)
mean(height)
```
```{r}
#d
#The relationship could exist as larger feet are often associated with taller individuals.
```

```{r}
#2
#a
Months <- c("March","April","January","November","January",
"September","October","September","November","August",
"January","November","November","February","May","August","July","December","August","August","September","November","February","April")

Factor_Months <- factor(Months)
Factor_Months
```


```{r}
#3
summary(Months)
summary(Factor_Months)

#Factor_Months is more useful, especially for analysis that involve categorical data, as it allows to treat the month names as categories rather than just strings.

```

```{r}
#4
direction <- c("East", "West", "North")
frequency <- c(1, 4, 3)

neworderdata <- factor(direction,levels = c("East","West","North"))
neworderdata
```
```{r}
#5
options(repos = c(CRAN = "https://cloud.r-project.org"))
install.packages("readxl")
data <- read.table("ExcelData.csv", header = TRUE, sep = ",", stringsAsFactors =  FALSE)
data
```
```{r}
#6
user_input <- readline(prompt = "Please enter a number between 1 and 50: ")
paste("The number you selected is:", user_input)

  if(is.na(user_input) < 1 && user_input > 50) {
    cat("The number selected is beyond the range of 1 to 50\n")
  } else if (user_input == 20) {
    cat("TRUE\n")
  } else {
    cat("You selected: ", user_input, "\n")
  }
```
```{r}
#7
min_bills <- function(price) {
  bills <- c(1000, 500, 200, 100, 50)
  

  count <- 0
  
  for (bill in bills) {
    if (price <= 0) {
      break
    }
    count <- count + floor(price / bill)
    
    price <- price %% bill
  }
  
  return(count)
}


snack_price <- as.integer(readline(prompt = "Enter the price of the snack (divisible by 50): "))
if (is.na(snack_price) %% 50 == 0) {
  cat("Minimum number of bills needed:", min_bills(snack_price), "\n")
} else {
  cat("The price must be divisible by 50.\n")
}
```
```{r}
#8
#a
Grades <- data.frame (Name = c("Annie", "Thea", "Steve", "Hanna"),
                       Grade_1 = c(85, 65, 75, 95),
                       Grade_2 = c(65, 75, 55, 75),
                       Grade_3 = c(85, 90, 80, 100),
                       Grade_4 = c(100, 90, 85, 90)
                       )
Grades
```


```{r}
#b
for (i in 1:nrow(Grades)) {
  avg_score <- sum(Grades[i, 2:5]) / 4
  if (avg_score > 90) {
    cat(Grades$Name[i], "'s average grade this semester is", avg_score, "\n")
  }
}
```


```{r}
#c
for (j in 2:ncol(Grades)) {
  test_avg <- sum(Grades[, j]) / nrow(Grades)
  if (test_avg < 80) {
    cat("The", colnames(Grades)[j], "test was difficult.\n")
  }
}
```
```{r}
#d
for (i in 1:nrow(Grades)) {
  highest_grade <- Grades[i, 2]
  for (j in 3:5) {
    if (Grades[i, j] > highest_grade) {
      highest_grade <- Grades[i, j]
    }
  }
  if (highest_grade > 90) {
    cat(Grades$Name[i], "'s highest grade this semester is", highest_grade, "\n")
  }
}
```



