---
title: "RWorksheet_Lumauag#1.Rmd"
output: pdf_document
date: "2024-09-17"
---

#1 
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29,
         35, 31, 27, 22, 37, 34, 19, 20, 57, 49,
         50, 37, 46, 25, 17, 37, 42, 53, 41, 51,
         35, 24, 33, 41)


#Rcode and output 
age_data_points <- length(age)
age_data_points

#2 
reciprocal_age <- 1 / age
reciprocal_age

#3
new_age <- c(age, 0, age)
new_age

#What happen to the new_age?
#It concantenates the age verctor, 0, and the age again. 

#4
sort(age)

#5
max(age)
min(age)

#6
data <- c(2.4, 2.8, 2.1, 2.5, 2.4, 2.2, 2.5,
2.3, 2.5, 2.3, 2.4, 2.7)

data_data_points <- length(data)
data_data_points

#7 
doubled_age <- age * 2
doubled_age

#What happen to the data? Each value of data in the age vector was multiplied by 2

#8

#a
length8_1 <- length(sequence1to100)
length8_2 <- length(sequence_20_60)
length8_3 <- length(mean_20_60)
length8_4 <- length(sumOf51to91)

total_length <- sum(length8_1, length8_2, length8_3, length8_4)
total_length

Total number of data points = 100 (8.1) + 41 (8.2) + 1 (8.3) + 1 (8.4) = 143 data points

#b
#8.1
sequence1to100 <- seq(1:100)
sequence1to100

#8.2
sequence_20_60 <- seq(20:60)
sequence_20_60

#8.3
mean_20_60 <- mean(20:60)
mean_20_60

#8.4
sumOf51to91 <- sum(51:91)
sumOf51to91

#8.5
sequence1to1000 <- seq(1:1000)
sequence1to1000


#c The maximum data point in this set is 10
sequence1to1000 <- seq(1:1000)
first10_elements <- sequence1to1000[1:10]
maxValueof_first_10 <- max(first10_elements)

first10_elements
maxValueof_first_10

#9
numbers <- 1:100
filtered_numbers <- Filter(function(i) { all(i %% c(3,5,7) != 0) }, seq(100))
filtered_numbers

#10
sequence1to100 <- seq(100:1)
sequence1to100

#11

#a Total number of data points from Tasks 10 to 11 is 112 data points, 100 (from Task 10) + 11 and 1 from sum of multiples (from Task 11) 

#b
upper_limit <- 24
numbersBelow25 <- 1:(upper_limit - 1)
multiplesOf3_or_5 <- Filter(function(i) { any(i %% c(3, 5) == 0) }, seq(24))
multiplesOf3_or_5

sum_multiples <- sum(multiplesOf3_or_5)
sum_multiples


#12
x <- {0 + x + 5 + }

#The statement x <- {0 + x + 5 + } results in an incomplete expression error.

#13
score <- c(72, 86, 92, 63, 88, 89, 91, 92, 75,
75, 77)

score [2]
score [3]

#14
a <- c(1,2,NA,4,NA,6,7)
print(a,na.print="999")
#The NA values has been replaced to 999.

#15
name = readline(prompt="Input your name: ")
age = readline(prompt="Input your age: ")
print(paste("My name is",name, "and I am",age ,"years old."))
print(R.version.string)

#The output was unorganized because of the format of functions.