---
title: "RWorksheet_Lumauag#4c"
author: "Matt Andrei Lumauag"
date: "2024-11-04"
output: pdf_document
---

```{r}
#1
#a
library(readxl)
dataset <- read.csv ("C:/RPROJS/mpg.csv")
dataset
```
```{r}
#b
#The categorical variables in the mpg dataset are manufacturer, model, trans, drv, fl, and class.
```

```{r}
#c
#The continuous variables in the mpg dataset are displ, cty, and hwy.
```

```{r}
#2
#The manufacturer with the most models in this dataset is Toyota, with 6 unique models. The model with the most variations is the Caravan 2WD, with 11 different configurations.
#a
library(ggplot2)
library(dplyr)
manufacturer_model_count <- dataset %>%
  group_by(manufacturer) %>%
  summarise(unique_models = n_distinct(model)) %>%
  arrange(desc(unique_models))

manufacturer_model_count
```
```{r}
#b
ggplot(manufacturer_model_count, aes(x = reorder(manufacturer, -unique_models), y = unique_models)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(title = "Unique Models by Manufacturer", x = "Manufacturer", y = "Count") + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r}
#2
#a
ggplot(mpg, aes(model, manufacturer)) + geom_point()
#It creates a scatter plot where each point represents a specific model-manufacturer combination. 
```
```{r}
#b
#It is useful but the x-axis have too many categories, making the plot cluttered and unreadable.
```

```{r}
#3
library(ggplot2)
library(dplyr)

top20data <- dataset %>% head(20)

ggplot(top20data, aes(x = model, y = year)) +
  geom_point() +
  labs(title = "Top 20 Car Models by Year") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
#4
modelcount <- dataset %>%
  group_by(model) %>%
  summarise(car_count = n())

modelcount
```
```{r}
#a
top_20_models <- modelcount %>% top_n(20, car_count)

ggplot(top_20_models, aes(x = reorder(model, car_count), y = car_count, fill = model)) +
  geom_bar(stat = "identity") +
  labs(title = "Top 20 Car Models by Count (Flipped)",
       x = "Car Model",
       y = "Count") 
```
```{r}
#b
ggplot(top_20_models, aes(x = reorder(model, car_count), y = car_count, fill = model)) +
  geom_bar(stat = "identity") +
  labs(title = "Top 20 Car Models by Count",
       x = "Car Model",
       y = "Count") + coord_flip() 
```
```{r}
#5
#a
#I observed that points with higher cylinder counts (cyl) align with higher values of engine displacement (displ).

ggplot(dataset, aes(x = cyl, y = displ, color = displ)) +
  geom_point() +
  labs(title = "Relationship between No. of Cylinders and Engine Displacement",
       x = "Number of Cylinders",
       y = "Engine Displacement (L)") 
```
```{r}
#6
ggplot(dataset, aes(x = displ, y = hwy, color = cyl)) +
  geom_point() +
  labs(title = "Relationship between Engine Displacement and Highway MPG",
       x = "Engine Displacement (L)",
       y = "Highway MPG")
```
```{r}
#7
library(readxl)
alexa_file <- read_excel("C:/RPROJS/alexa_file.xlsx")
alexa_file
```
```{r}
#a
num_rows <- nrow(alexa_file)
num_cols <- ncol(alexa_file)
cat("Number of observations:", num_rows, "\n")
cat("Number of columns:", num_cols, "\n")
```
```{r}
#b
library(dplyr)

variations_count <- alexa_file %>%
  group_by(variation) %>%
  summarise(total_count = n())

variations_count
```
```{r}
#c
install.packages("ggplot2")
library(ggplot2)

variation_plot <- ggplot(variations_count, aes(x = variation, y = total_count)) +
  geom_bar(stat = "identity") +
  xlab("Variations") +
  ylab("Total Count") +
  ggtitle("Total Count of Each Variation")

variation_plot
```
```{r}
#d
library(dplyr)
numofverifiedviews <- alexa_file %>%
  group_by(date) %>%
  summarise(count = n()) %>%
  arrange(date)

verified_reviews_plot <- ggplot(numofverifiedviews, aes(x = date, y = count)) +
  geom_line(color = "black") +
 labs(title = "Verified Reviews Over Time", x = "Date", y = "Verified Reviews") +
  theme_minimal()


verified_reviews_plot
```
```{r}
#e
colnames(alexa_file)
variation_rate <- alexa_file %>%
  group_by(variation) %>%
  summarise(avg_rating = mean(rating, na.rm = TRUE)) %>%
  arrange(desc(avg_rating))
variation_rate

ggplot(variation_rate, aes(x = reorder(variation, avg_rating), y = avg_rating, fill = variation)) +
  geom_bar(stat = "identity") + labs(title = "Average Ratings by Variation", x = "Variation", y = "Average Rating") + coord_flip()
```















